### ISSUE TITLE
Incompatible with tox 3.8.0

### ISSUE THREAD

**Issue by stinovlas** [balabit/tox-debian-plugin#13]
This plugin fails with the lastest release of tox 3.8.0 that apparently introduced some breaking changes.

```
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/local/lib/python3.5/dist-packages/tox/session/__init__.py", line 42, in cmdline
    main(args)
  File "/usr/local/lib/python3.5/dist-packages/tox/session/__init__.py", line 63, in main
    retcode = session.runcommand()
  File "/usr/local/lib/python3.5/dist-packages/tox/session/__init__.py", line 187, in runcommand
    return self.subcommand_test()
  File "/usr/local/lib/python3.5/dist-packages/tox/session/__init__.py", line 215, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/usr/local/lib/python3.5/dist-packages/tox/session/commands/run/sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "/usr/local/lib/python3.5/dist-packages/tox/venv.py", line 582, in setupenv
    status = self.update(action=action)
  File "/usr/local/lib/python3.5/dist-packages/tox/venv.py", line 245, in update
    self.hook.tox_testenv_install_deps(action=action, venv=self)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 68, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pluggy/manager.py", line 62, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/usr/local/lib/python3.5/dist-packages/tox_DEBIAN/__init__.py", line 49, in tox_testenv_install_deps
    action
  File "/usr/local/lib/python3.5/dist-packages/tox_DEBIAN/install.py", line 23, in install_debian_deps
    action.popen(['apt-get', 'download'] + opts + deps, cwd=tmp_dir)
  File "/usr/local/lib/python3.5/dist-packages/tox/action.py", line 102, in popen
    reporter.log_popen(cwd, out_path, cmd_args_shell, process.pid)
  File "/usr/local/lib/python3.5/dist-packages/tox/reporter.py", line 48, in log_popen
    if outpath.common(cwd) is not None:
  File "/usr/local/lib/python3.5/dist-packages/py/_path/common.py", line 336, in common
    for x, y in zip(self.parts(), other.parts()):
AttributeError: 'str' object has no attribute 'parts'
```

**Comment by tpazderka** [comment]
Forked and released on PyPi as `tox_DEBIAN 0.2` if anyone is interested.
